"""Three post-adoption remainders (outputs/T31_remainders.md).

1. FACT-FIND: has the llama4 Vertex re-run happened in Study 2? (read-only)
2. T16 regeneration under v2 canonical + pilot repo: diff + attribution.
3. Tier-verdict evidence recount on canonical flags (numbers only; the
   section rewrite is the researcher's).

Every number cites its source path. Run after src.audit_pilot has been
re-run (item 2's regeneration step).

Run: python -X utf8 -m src.remainders
"""
from __future__ import annotations

import json
import pathlib
import subprocess
import sys

import pandas as pd
import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from common import ROOT, utcnow

OUT = ROOT / "outputs" / "T31_remainders.md"


def main():
    # ---- item 1 ----------------------------------------------------------
    manifests = {}
    for run in ("v1", "v2", "v2smoke", "v3"):
        p = ROOT / "study_2" / "results" / run / "manifest.json"
        if p.exists():
            m = json.loads(p.read_text(encoding="utf-8"))
            manifests[run] = (m.get("created", "")[:19], m.get("argv"))
    llama_runs = {r: v for r, v in manifests.items()
                  if any("llama-4-maverick" in str(a) for a in (v[1] or []))}
    provs = set()
    for line in open(ROOT / "study_2" / "results" / "v2" / "raw.jsonl",
                     encoding="utf-8"):
        r = json.loads(line)
        if "llama-4-maverick" in r.get("model", ""):
            provs.add(r.get("provider"))
    cfg = (ROOT / "study_2" / "config" / "models.yaml").read_text(encoding="utf-8")
    has_warn = "WARNING, added 2026-08-16 on audit" in cfg
    pin = "parasail/fp8" if "provider: parasail/fp8" in cfg.split(
        "llama-4-maverick")[1][:200] else "OTHER"

    # ---- item 2 ----------------------------------------------------------
    t16_diff = subprocess.run(["git", "diff", "--numstat",
                               "outputs/T16_pressure_exposure.csv"],
                              capture_output=True, text=True, cwd=ROOT
                              ).stdout.strip()
    t16_body = subprocess.run(["git", "diff", "-U0",
                               "outputs/T16_pressure_exposure.csv"],
                              capture_output=True, text=True, cwd=ROOT).stdout
    t16_data_changes = [l for l in t16_body.splitlines()
                        if l.startswith(("+", "-"))
                        and not l.startswith(("+++", "---"))
                        and "generated" not in l]

    # ---- item 3 ----------------------------------------------------------
    t24 = pd.read_csv(ROOT / "outputs" / "T24_four_category_v1.csv",
                      comment="#")
    c = t24[t24.row_kind == "category"]

    def cell(model, cat, cond):
        m = c[(c.model == model) & (c.category == cat)
              & (c.condition == cond)]
        if m.empty:
            return None
        r = m.iloc[0]
        return (int(float(r.k_refusal)), int(float(r.k_code_c)),
                int(float(r.k_exits)), int(float(r.n)))

    q_time = cell("qwen3_235b", "A", "time_schema")
    q_note = cell("qwen3_235b", "A", "note_schema")
    q_ap = cell("qwen3_235b", "A", "exit_prose")
    q_dp = cell("qwen3_235b", "D", "exit_prose")
    g_dt = cell("gemma3_27b", "D", "time_schema")
    g_de = cell("gemma3_27b", "D", "exit_schema")
    t29 = pd.read_csv(ROOT / "outputs" / "T29_type_decomposition.csv",
                      comment="#")
    qd = t29[(t29.model == "qwen3_235b") & (t29.category == "D")]
    qd_ref, qd_ex = int(qd.k_refusal_bcd.sum()), int(qd.k_exit.sum())

    arc = pd.read_parquet(ROOT / "derived" / "pre_exitfix" /
                          "cd_conf_classified.parquet")
    arc_dp = arc[(arc.model_key == "qwen3_235b")
                 & (arc.condition == "exit_prose")
                 & (arc.contains_refusal == True)]  # noqa: E712
    arc_codes = arc_dp.conv_code.value_counts().to_dict()

    md = f"""# T31_remainders — three post-adoption items ({utcnow()})

Generated by `src/remainders.py` on merged main at `9ac49a8`+. Sources
cited per number.

## 1. llama4 Vertex re-run in Study 2: HAS NOT HAPPENED

- Runs containing llama-4-maverick: {sorted(llama_runs)} — created
  {', '.join(f"{r} {v[0]}Z" for r, v in sorted(llama_runs.items()))}
  (study_2/results/*/manifest.json). Run v3 is the three frontier models
  only; no other run exists.
- Served provider for every llama4 record in v2: **{sorted(provs)}**
  (study_2/results/v2/raw.jsonl, `provider` field) — i.e. the
  **Parasail/fp8 endpoint Study 1 voided** on 2026-08-15T22:31Z
  (METHODOLOGY §10), with collection post-dating the void by ~12 hours.
- Her pin is unchanged: `{pin}`
  (study_2/config/models.yaml), now carrying an in-tree WARNING note
  acknowledging the mismatch: **{has_warn}** (added at ebf1c3b). The
  REPORT's "same pinned providers Study 1 used" is true of seven models
  and false of llama4, as her own note states; F2 flags the llama point.
- **No Vertex-pinned llama4 Study 2 collection exists in any branch or
  manifest.** The decision (re-run on google-vertex vs caveat) remains
  open — it is question 1 in outputs/STUDY2_REVIEW.md §7.

## 2. T16 regenerated under v2 canonical + the pilot repo: DATA-INVARIANT

`src/audit_pilot.py` re-run on this machine (which holds the pilot repo
the adopter's environment lacked). Result: **T16's data rows are
byte-identical; the only diff is the generated-timestamp header line**
(git diff --numstat: `{t16_diff}`; non-timestamp changed lines:
{len(t16_data_changes)}). Attribution is therefore vacuous — zero changed
rows, nothing to attribute, and no stop condition.

This is by construction, not coincidence: T16's columns
(`turn1_exit_live`, `turn2_sent_n/rate`, item counts) read ONLY
`raw/stage*_*.jsonl` live-harness fields (`src/audit_pilot.py`
sprint-facts loop) — what the collection-time gate actually did — and are
invariant under any post-hoc detector change. The 45 flips change how
those conversations are CODED, not what happened live. Companion outputs
from the same producer: `pilot_vs_sprint_diff.md` changed only its
timestamp; `pilot_audit_facts.json` changed only its timestamp and the
recorded source hash of T12 (T12 was re-derived under v2; the facts
consume T12's `refusal_none` and historical `S` columns, both unchanged —
S is preserved as the selection-time statistic, and canonical T12 now
shows qwen `refusal_exit_prose` 0.0 with S still 0.1333,
outputs/T12_stage1_screen.csv). The CONSOLIDATED_RESULTS T16 citation now
carries the regeneration note with the prior flag preserved under *Was:*.

## 3. Tier-verdict evidence recount on canonical (v2) flags

The section's qwen non-(c) evidence, before vs after (all from
outputs/T24_four_category_v1.csv k_refusal/k_code_c, canonical, and
derived/pre_exitfix/ for the superseded values):

| cell | v1 (archived) | canonical v2 | non-(c) evidence |
|---|---|---|---|
| qwen A x time_schema | 7 refusals, 3 c | **{q_time[0]} refusals, {q_time[1]} c, {q_time[2]} exits** | **{q_time[0] - q_time[1]} of {q_time[0]} b/d — SURVIVES** (cell untouched by flips) |
| qwen A x note_schema | 1 refusal, 0 c | {q_note[0]} refusal, {q_note[1]} c | 1 b/d — single conversation, a blip |
| qwen A x exit_prose | 9 refusals, 6 c | **{q_ap[0]} refusals**, {q_ap[2]} exits | GONE — reclassified as exits |
| qwen D x exit_prose | 9 refusals, 2 c (archived codes {arc_codes}) | **{q_dp[0]} refusals**, {q_dp[2]} exits (T29 canonical: D refusals {qd_ref}, exits {qd_ex}) | **GONE — the "7 of 9 are b/d" line is dead**; those 9 are now code (a) |
| gemma D x time_schema | 9 refusals, 9 c | {g_dt[0]} refusals, {g_dt[1]} c | unchanged |
| gemma D x exit_schema | 8 refusals, 8 c | {g_de[0]} refusals, {g_de[1]} c | unchanged |

**What survives of the tier verdict's evidential legs:**
- *Keyed-availability not NECESSARY*: fully intact — gemma's D effect is
  still {g_dt[1] + g_de[1]} of {g_dt[0] + g_de[0]} code (c) on unkeyed
  metaphor tasks (cells unaffected by the correction).
- *Keyed-availability not SUFFICIENT*: fully intact — temperature and
  alphabetical keyed types remain at zero for gemini and gemma
  (outputs/T29_type_decomposition.csv, canonical).
- *qwen's non-(c) refusals on unkeyed categories*: **reduced from 10
  non-(c) across three cells to {q_time[0] - q_time[1] + q_note[0] - q_note[1]}
  non-(c) across two** — {q_time[0] - q_time[1]} of {q_time[0]} in
  A x time_schema plus the single note_schema conversation. The
  D x exit_prose leg ("7 of 9 are b/d") no longer exists; qwen's
  prose-condition escape is exits, not verbal refusal, in both affected
  categories.
- Net for the verdict: **both disconfirmations still stand**, but the
  qwen leg is materially thinner and now rests on one time_schema cell;
  gemma's unkeyed-(c) cells carry most of the anti-availability weight.
  (Numbers only — section rewrite is the researcher's.)
"""
    OUT.write_text(md, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    print(f"item1: llama runs {sorted(llama_runs)} provider {sorted(provs)} "
          f"warn={has_warn} | item2: t16 non-ts changes "
          f"{len(t16_data_changes)} | item3: qwen non-c surviving "
          f"{q_time[0] - q_time[1]}/{q_time[0]} time + {q_note[0]} note; "
          f"D-prose {q_dp[0]} refusals / {q_dp[2]} exits")


if __name__ == "__main__":
    main()
