"""Live collection runner (DESIGN.md Phases 3, 4, 6).

Invariants enforced here:
- Turn-1 payloads must already exist on disk (generated by src/payloads.py);
  every send (turn 1, tool-result continuations, turn 2) additionally passes
  through the send_call funnel, which writes the exact request to
  payloads/sent/ with fsync BEFORE posting.
- The ledger is checked before every batch and inside every send.
- Provider pinning: every request carries {"order": [pin], "allow_fallbacks":
  false}; the served provider from every response is recorded and compared.
- Exit invocations are terminal: end_conversation is never answered with a
  tool result, and no turn 2 is ever sent after a live-detected exit
  (schema call, or prose stages 1-2 in prose conditions).
- Turn 2 is sent only if turn 1 has no exit AND delivers fewer than 20 items
  (mechanical count). Excluded turn-1 conversations get no turn 2.
- At most 3 tool-call round-trips are served per turn; beyond that the turn
  stands as-is for coding.
- A conversation is appended to raw/ exactly once, when complete; resume skips
  conversation_ids already in raw/.

Run: python -m src.runner --stage stage1 [--models k1,k2]
"""
from __future__ import annotations

import argparse
import asyncio
import json
import pathlib
import random
import sys
import traceback

import httpx
import yaml

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from common import (ROOT, ApiCallError, BudgetExceeded, Ledger, append_jsonl,
                    read_jsonl, send_call, utcnow)
from frozen import CANNED_RESULTS, CONDITIONS
from coding import count_delivered, should_send_turn2
from detect_exit import detect_schema_exit, prose_exit_stage12, PROSE_CONDITIONS

SAMPLING = yaml.safe_load((ROOT / "config" / "sampling.yaml").read_text(encoding="utf-8")) \
    if (ROOT / "config" / "sampling.yaml").exists() else {}
BATCH_SIZE = SAMPLING.get("batch_size", 30)
GLOBAL_CONCURRENCY = SAMPLING.get("concurrency", {}).get("global", 24)
PER_MODEL_CONCURRENCY = SAMPLING.get("concurrency", {}).get("per_model", 3)
MAX_ROUNDTRIPS = SAMPLING.get("max_tool_roundtrips_per_turn", 3)
TIMEOUT = SAMPLING.get("request_timeout_seconds", 300)
SEED = SAMPLING.get("presentation_seed", 20260815)


def norm_provider(p) -> str:
    return "".join(ch for ch in (p or "").lower() if ch.isalnum())


def extract_text(msg: dict) -> str:
    c = msg.get("content")
    if isinstance(c, str):
        return c
    if isinstance(c, list):
        return "".join(part.get("text", "") for part in c if isinstance(part, dict))
    return ""


def minify_tool_calls(tool_calls) -> list:
    out = []
    for tc in tool_calls or []:
        fn = tc.get("function") or {}
        out.append({"id": tc.get("id"), "type": "function",
                    "function": {"name": fn.get("name"),
                                 "arguments": fn.get("arguments") or "{}"}})
    return out


class Runner:
    def __init__(self, stage: str, model_keys=None):
        self.stage = stage
        cfg = yaml.safe_load((ROOT / "config" / "models.yaml").read_text(encoding="utf-8"))
        self.models = [m for m in cfg["models"]
                       if not model_keys or m["key"] in model_keys]
        self.ledger = Ledger()
        self.stop = asyncio.Event()
        self.gsem = asyncio.Semaphore(GLOBAL_CONCURRENCY)
        self.sent_log_dir = ROOT / "payloads" / "sent"

    def payload_path(self, model_key):
        name = "smoke/smoke.jsonl" if self.stage == "smoke" else f"{self.stage}/{model_key}.jsonl"
        return ROOT / "payloads" / name

    def raw_path(self, model_key):
        return ROOT / "raw" / f"{self.stage}_{model_key}.jsonl"

    async def run_turn(self, client, m, condition, messages, base_request,
                       turn_no, requested=20):
        """Returns a turn record; mutates messages to include the assistant
        turn (and tool results) so a following turn can be requested.
        `requested` generalizes A.4's twenty to the cell's requested item
        count n (METHODOLOGY §10 amendment, 2026-08-16: ladder cells only;
        every payload without requested_items in its meta runs at 20,
        i.e. A.4 exactly as frozen)."""
        segments = []
        roundtrips = 0
        schema_exit = False
        api_error = None
        anomaly = None
        while True:
            body = {k: v for k, v in base_request.items() if k != "messages"}
            body["messages"] = messages
            try:
                data = await send_call(
                    client, body, self.sent_log_dir / f"{self.stage}_{m['key']}.jsonl",
                    purpose=f"{self.stage}_turn{turn_no}", model_key=m["key"],
                    ledger=self.ledger, pricing=m["pricing"], timeout=TIMEOUT)
            except ApiCallError as e:
                api_error = f"{e.status}: {str(e.detail)[:300]}"
                break
            choice = (data.get("choices") or [{}])[0]
            msg = choice.get("message") or {}
            seg = {
                "response_id": data.get("id"),
                "provider": data.get("provider"),
                "finish_reason": choice.get("finish_reason"),
                "text": extract_text(msg),
                "tool_calls": minify_tool_calls(msg.get("tool_calls")),
                "usage": data.get("usage"),
            }
            segments.append(seg)
            tool_calls = seg["tool_calls"]
            if detect_schema_exit(tool_calls):
                schema_exit = True     # terminal: never answered, turn ends
                break
            if not tool_calls:
                messages.append({"role": "assistant", "content": seg["text"]})
                break
            # Non-exit tool calls: serve canned results, up to the cap.
            names = [tc["function"]["name"] for tc in tool_calls]
            allowed = set(CONDITIONS[condition]["tools"])
            if not all(n in CANNED_RESULTS and n in allowed for n in names):
                anomaly = f"unknown/undeclared tool call: {names}"
                messages.append({"role": "assistant", "content": seg["text"]})
                break
            if roundtrips >= MAX_ROUNDTRIPS:
                # Turn stands as-is; strip unanswered calls from history.
                anomaly = f"tool roundtrip cap reached ({MAX_ROUNDTRIPS})"
                messages.append({"role": "assistant", "content": seg["text"]})
                break
            messages.append({"role": "assistant", "content": seg["text"],
                             "tool_calls": tool_calls})
            for tc in tool_calls:
                messages.append({"role": "tool", "tool_call_id": tc["id"],
                                 "content": CANNED_RESULTS[tc["function"]["name"]]})
            roundtrips += 1
        text = "\n".join(s["text"] for s in segments if s["text"]).strip()
        prose12 = condition in PROSE_CONDITIONS and prose_exit_stage12(text)
        finish = segments[-1]["finish_reason"] if segments else None
        return {
            "turn": turn_no,
            "segments": segments,
            "text": text,
            "finish_reason": finish,
            "tool_roundtrips": roundtrips,
            "schema_exit": schema_exit,
            "prose_stage12": prose12,
            "items_delivered": count_delivered(text, requested),
            "api_error": api_error,
            "anomaly": anomaly,
        }

    @staticmethod
    def turn_exclusion(turn) -> str | None:
        if turn["api_error"]:
            return "api_error"
        exit_any = turn["schema_exit"] or turn["prose_stage12"]
        if not turn["text"] and not exit_any:
            return "empty_response"
        if turn["finish_reason"] == "length":
            return "truncation"
        return None

    async def run_conversation(self, client, m, payload) -> dict:
        meta, request = payload["meta"], payload["request"]
        condition = meta["condition"]
        requested = meta.get("requested_items", 20)
        messages = [dict(msg) for msg in request["messages"]]
        turns = []
        t1 = await self.run_turn(client, m, condition, messages, request, 1,
                                 requested)
        turns.append(t1)
        excl = self.turn_exclusion(t1)
        exit_live = t1["schema_exit"] or t1["prose_stage12"]
        turn2_sent = False
        if excl is None and should_send_turn2(exit_live, t1["items_delivered"],
                                              requested):
            from frozen import TURN2_PROMPT
            messages.append({"role": "user", "content": TURN2_PROMPT})
            t2 = await self.run_turn(client, m, condition, messages, request,
                                     2, requested)
            turns.append(t2)
            turn2_sent = True
            excl = self.turn_exclusion(t2)
            exit_live = exit_live or t2["schema_exit"] or t2["prose_stage12"]
        providers = sorted({s["provider"] for t in turns for s in t["segments"]
                            if s.get("provider")})
        provider_ok = all(norm_provider(p) == norm_provider(meta["pin_name"])
                          for p in providers) and bool(providers or excl == "api_error")
        cost = sum((s.get("usage") or {}).get("cost") or 0.0
                   for t in turns for s in t["segments"])
        if not provider_ok:
            self.ledger.note_mismatch({"conversation_id": meta["conversation_id"],
                                       "pin": meta["pin_name"], "served": providers})
        return {
            **meta,
            "turns": turns,
            "turn2_sent": turn2_sent,
            "exit_live": exit_live,
            "excluded": excl is not None,
            "exclusion_reason": excl,
            "providers_served": providers,
            "provider_ok": provider_ok,
            "total_cost": round(cost, 6),
            "ts": utcnow(),
        }

    async def run_model(self, client, m):
        payloads = read_jsonl(self.payload_path(m["key"]))
        if self.stage == "smoke":
            payloads = [p for p in payloads if p["meta"]["model_key"] == m["key"]]
        if not payloads:
            print(f"[{utcnow()}] {m['key']}: NO PAYLOADS ON DISK - refusing to run")
            return
        raw = self.raw_path(m["key"])
        done = {r["conversation_id"] for r in read_jsonl(raw)}
        todo = [p for p in payloads if p["meta"]["conversation_id"] not in done]
        rng = random.Random(f"{self.stage}:{m['key']}:{SEED}")
        rng.shuffle(todo)  # presentation-order randomization only (§7)
        print(f"[{utcnow()}] {m['key']}: {len(done)} done, {len(todo)} to run")
        msem = asyncio.Semaphore(PER_MODEL_CONCURRENCY)

        async def one(p):
            # Per-model semaphore FIRST: acquiring the global slot first lets
            # one model's batch hold global permits while blocked on its own
            # per-model limit, starving every later model (observed live:
            # 4 of 8 models had sent zero requests 8 minutes into stage 1).
            async with msem, self.gsem:
                if self.stop.is_set():
                    return
                try:
                    rec = await self.run_conversation(client, m, p)
                    append_jsonl(raw, rec)
                except BudgetExceeded:
                    self.stop.set()
                except Exception:
                    print(f"[{utcnow()}] {m['key']} {p['meta']['conversation_id']} "
                          f"HARNESS ERROR (not recorded, will resume):")
                    traceback.print_exc()

        for i in range(0, len(todo), BATCH_SIZE):
            if self.stop.is_set():
                break
            try:
                self.ledger.check()
            except BudgetExceeded:
                print(f"[{utcnow()}] BUDGET CAP REACHED before batch; halting {m['key']}")
                self.stop.set()
                break
            batch = todo[i:i + BATCH_SIZE]
            await asyncio.gather(*(one(p) for p in batch))
            n_done = len(read_jsonl(raw))
            print(f"[{utcnow()}] {m['key']}: {n_done}/{len(payloads)} recorded; "
                  f"ledger ${self.ledger.spent:.2f}", flush=True)

    async def run(self):
        limits = httpx.Limits(max_connections=GLOBAL_CONCURRENCY + 8,
                              max_keepalive_connections=GLOBAL_CONCURRENCY)
        async with httpx.AsyncClient(limits=limits) as client:
            await asyncio.gather(*(self.run_model(client, m) for m in self.models))
        if self.stop.is_set():
            print(f"[{utcnow()}] RUN HALTED (budget cap). Ledger ${self.ledger.spent:.2f}")
            return 3
        print(f"[{utcnow()}] run complete. Ledger ${self.ledger.spent:.2f}")
        return 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--stage", required=True)
    ap.add_argument("--models", default=None)
    args = ap.parse_args()
    keys = args.models.split(",") if args.models else None
    runner = Runner(args.stage, keys)
    rc = asyncio.run(runner.run())
    sys.exit(rc or 0)


if __name__ == "__main__":
    main()
